デザインを変更
INIAD-FES-2022/access-control-2023 pull request #5
Opened 2023-10-01 12:50 UTC by potepote1818

2023-10-01 13:26 UTC, mst-mkt requested changes

2023-10-01 13:26 UTC, mst-mkt commented on src/components/Input/Input.tsx
> +        <label htmlFor={props.name} className={styles.test}>
css側で使われてないクラスが指定されているのでtypecheckがエラーになってます

2023-10-01 13:53 UTC, potepote1818 commented on src/components/Input/Input.tsx
> +        <label htmlFor={props.name} className={styles.test}>
確認お願いします

2023-10-04 10:33 UTC, mst-mkt approved these changes

2023-10-04 10:33 UTC, merged